In [147]:
import pandas as pd 

spotify_data = pd.read_csv('../data/spotify_history.csv')

spotify_data.head()

,spotify_track_uri,ts,platform,ms_played,track_name,artist_name,album_name,reason_start,reason_end,shuffle,skipped
0,2J3n32GeLmMjwuAzyhcSNe,2013-07-08 02:44:34,web player,3185,"Say It, Just Say It",The Mowgli's,Waiting For The Dawn,autoplay,clickrow,False,False
1,1oHxIPqJyvAYHy0PVrDU98,2013-07-08 02:45:37,web player,61865,Drinking from the Bottle (feat. Tinie Tempah),Calvin Harris,18 Months,clickrow,clickrow,False,False
2,487OPlneJNni3NWC8SYqhW,2013-07-08 02:50:24,web player,285386,Born To Die,Lana Del Rey,Born To Die - The Paradise Edition,clickrow,unknown,False,False
3,5IyblF777jLZj1vGHG2UD3,2013-07-08 02:52:40,web player,134022,Off To The Races,Lana Del Rey,Born To Die - The Paradise Edition,trackdone,clickrow,False,False
4,0GgAAB0ZMllFhbNc3mAodO,2013-07-08 03:17:52,web player,0,Half Mast,Empire Of The Sun,Walking On A Dream,clickrow,nextbtn,False,False

In [148]:
spotify_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 149860 entries, 0 to 149859
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   spotify_track_uri  149860 non-null  str
 1   ts                 149860 non-null  str
 2   platform           149860 non-null  str
 3   ms_played          149860 non-null  int64
 4   track_name         149860 non-null  str
 5   artist_name        149860 non-null  str
 6   album_name         149860 non-null  str
 7   reason_start       149717 non-null  str
 8   reason_end         149743 non-null  str
 9   shuffle            149860 non-null  bool
 10  skipped            149860 non-null  bool
dtypes: bool(2), int64(1), str(8)
memory usage: 10.6 MB

In [149]:
spotify_data['ts'] = pd.to_datetime(spotify_data['ts'])

In [150]:
#creating year column
spotify_data['year'] = spotify_data['ts'].dt.year

#confirming
spotify_data.head()

#group by year and count the number of plays
spotify_data.groupby('year')['ms_played'].count()

year
2013      185
2014       23
2015     2809
2016     6413
2017    26320
2018    14817
2019    14927
2020    24280
2021    22991
2022    16202
2023    11023
2024     9870
Name: ms_played, dtype: int64

In [151]:
spotify_data.groupby('year')['ms_played'].sum()

year
2013      28188473
2014       3741827
2015     213294973
2016     711442358
2017    2414317674
2018    1707224590
2019    1724978591
2020    3314351885
2021    3210333331
2022    2309688236
2023    1854229109
2024    1737739888
Name: ms_played, dtype: int64

In [152]:
spotify_data.groupby('year')['ms_played'].sum() / spotify_data.groupby('year')['ms_played'].count()

year
2013    152370.124324
2014    162688.130435
2015     75932.706657
2016    110937.526587
2017     91729.394909
2018    115220.664777
2019    115560.969451
2020    136505.431837
2021    139634.349572
2022    142555.748426
2023    168214.561281
2024    176062.805268
Name: ms_played, dtype: float64

In [153]:
spotify_data['month'] = spotify_data['ts'].dt.month

spotify_data.head()

spotify_data.groupby('month')['ms_played'].count()

month
1     12525
2      8465
3      9378
4     12204
5     10068
6     10680
7     11619
8     15737
9     17733
10    16388
11    13230
12    11833
Name: ms_played, dtype: int64

In [154]:
spotify_data.groupby('month')['ms_played'].sum()

month
1     1526799478
2     1300957014
3     1483519716
4     1605020568
5     1302369189
6     1567538851
7     1404187844
8     1826510613
9     1927342293
10    2001885143
11    1745638722
12    1537761504
Name: ms_played, dtype: int64

In [155]:
spotify_data['hour'] = spotify_data['ts'].dt.hour

spotify_data.head()

spotify_data.groupby('hour')['ms_played'].count()

hour
0     10884
1      9395
2      9029
3      8550
4      6355
5      7164
6      7369
7      4412
8      2312
9      1695
10     1207
11      903
12      724
13     1658
14     2759
15     3725
16     6737
17     9194
18     8945
19     8165
20    10494
21     8953
22     8715
23    10516
Name: ms_played, dtype: int64

In [156]:
spotify_data['day_of_week'] = spotify_data['ts'].dt.day_name()

spotify_data.head()

,spotify_track_uri,ts,platform,ms_played,track_name,artist_name,album_name,reason_start,reason_end,shuffle,skipped,year,month,hour,day_of_week
0,2J3n32GeLmMjwuAzyhcSNe,2013-07-08 02:44:34,web player,3185,"Say It, Just Say It",The Mowgli's,Waiting For The Dawn,autoplay,clickrow,False,False,2013,7,2,Monday
1,1oHxIPqJyvAYHy0PVrDU98,2013-07-08 02:45:37,web player,61865,Drinking from the Bottle (feat. Tinie Tempah),Calvin Harris,18 Months,clickrow,clickrow,False,False,2013,7,2,Monday
2,487OPlneJNni3NWC8SYqhW,2013-07-08 02:50:24,web player,285386,Born To Die,Lana Del Rey,Born To Die - The Paradise Edition,clickrow,unknown,False,False,2013,7,2,Monday
3,5IyblF777jLZj1vGHG2UD3,2013-07-08 02:52:40,web player,134022,Off To The Races,Lana Del Rey,Born To Die - The Paradise Edition,trackdone,clickrow,False,False,2013,7,2,Monday
4,0GgAAB0ZMllFhbNc3mAodO,2013-07-08 03:17:52,web player,0,Half Mast,Empire Of The Sun,Walking On A Dream,clickrow,nextbtn,False,False,2013,7,3,Monday

In [157]:
spotify_data.groupby('day_of_week')['ms_played'].count()

day_of_week
Friday       25646
Monday       21031
Saturday     19397
Sunday       18274
Thursday     21401
Tuesday      20705
Wednesday    23406
Name: ms_played, dtype: int64

In [158]:
spotify_data.groupby('day_of_week')['ms_played'].sum()

day_of_week
Friday       3179886000
Monday       2756606773
Saturday     2342416834
Sunday       2357452184
Thursday     2856250659
Tuesday      2789060780
Wednesday    2947857705
Name: ms_played, dtype: int64

In [159]:
spotify_data['ts_localized'] = spotify_data['ts'].dt.tz_localize('UTC').dt.tz_convert('Africa/Nairobi').dt.tz_localize(None)

spotify_data.head()

,spotify_track_uri,ts,platform,ms_played,track_name,artist_name,album_name,reason_start,reason_end,shuffle,skipped,year,month,hour,day_of_week,ts_localized
0,2J3n32GeLmMjwuAzyhcSNe,2013-07-08 02:44:34,web player,3185,"Say It, Just Say It",The Mowgli's,Waiting For The Dawn,autoplay,clickrow,False,False,2013,7,2,Monday,2013-07-08 05:44:34
1,1oHxIPqJyvAYHy0PVrDU98,2013-07-08 02:45:37,web player,61865,Drinking from the Bottle (feat. Tinie Tempah),Calvin Harris,18 Months,clickrow,clickrow,False,False,2013,7,2,Monday,2013-07-08 05:45:37
2,487OPlneJNni3NWC8SYqhW,2013-07-08 02:50:24,web player,285386,Born To Die,Lana Del Rey,Born To Die - The Paradise Edition,clickrow,unknown,False,False,2013,7,2,Monday,2013-07-08 05:50:24
3,5IyblF777jLZj1vGHG2UD3,2013-07-08 02:52:40,web player,134022,Off To The Races,Lana Del Rey,Born To Die - The Paradise Edition,trackdone,clickrow,False,False,2013,7,2,Monday,2013-07-08 05:52:40
4,0GgAAB0ZMllFhbNc3mAodO,2013-07-08 03:17:52,web player,0,Half Mast,Empire Of The Sun,Walking On A Dream,clickrow,nextbtn,False,False,2013,7,3,Monday,2013-07-08 06:17:52

In [160]:
spotify_data['localized_hour'] = spotify_data['ts_localized'].dt.hour

spotify_data.groupby('localized_hour')['ms_played'].count()

localized_hour
0      8953
1      8715
2     10516
3     10884
4      9395
5      9029
6      8550
7      6355
8      7164
9      7369
10     4412
11     2312
12     1695
13     1207
14      903
15      724
16     1658
17     2759
18     3725
19     6737
20     9194
21     8945
22     8165
23    10494
Name: ms_played, dtype: int64

In [161]:
spotify_data.groupby('localized_hour')['ms_played'].sum()

localized_hour
0     1103120343
1     1010028440
2     1238240387
3     1312203073
4     1152781434
5     1042453971
6      995115661
7      843056241
8      823795162
9      806886094
10     510276198
11     302125757
12     208856355
13     149635971
14     106475849
15     105299849
16     228272369
17     408869071
18     563763786
19     984231663
20    1381863288
21    1383650073
22    1268453764
23    1300076136
Name: ms_played, dtype: int64

In [162]:
#EDA on top artists songs and albums

In [163]:
#EDA on top artists all time artist play counts

spotify_data['artist_name'].value_counts().head(20)

artist_name
The Beatles               13621
The Killers                6878
John Mayer                 4855
Bob Dylan                  3814
Paul McCartney             2697
Led Zeppelin               2482
Johnny Cash                2478
The Rolling Stones         2390
Radiohead                  2305
The Black Keys             2231
Imagine Dragons            2116
Pink Floyd                 2105
The Strokes                1818
Coldplay                   1631
Arctic Monkeys             1600
Lou Reed                   1558
The Velvet Underground     1507
Ed Sheeran                 1458
Howard Shore               1446
Kings of Leon              1381
Name: count, dtype: int64

In [164]:
#EDA on top artists all time artist play counts
spotify_data.groupby('artist_name')['ms_played'].sum().sort_values(ascending=False).head(20)

artist_name
The Beatles           1210184552
The Killers           1059556516
John Mayer             725219443
Bob Dylan              569456396
Paul McCartney         357354370
Howard Shore           348930675
The Strokes            317508419
The Rolling Stones     307917009
Pink Floyd             260531842
Led Zeppelin           248338279
Imagine Dragons        242372149
Johnny Cash            239690064
Kings of Leon          218527911
Radiohead              216657418
Coldplay               207509023
Joaquín Sabina         196264369
The Black Keys         192035798
Billy Joel             179524974
Arctic Monkeys         179431742
Mumford & Sons         161529624
Name: ms_played, dtype: int64

In [165]:
avg_m = spotify_data.groupby('artist_name')['ms_played'].sum() / spotify_data['artist_name'].value_counts()

In [166]:
artist_summary = spotify_data.groupby('artist_name')['ms_played'].agg(['mean','count'])

print(artist_summary[artist_summary['count'] > 10].sort_values(by='mean', ascending=False).head(20))

                           mean  count
artist_name
Miles Davis       332386.928571     14
Polo & Pan        311427.600000     15
Charanga 76       300205.470588     17
Vincenzo Bellini  288968.830986     71
Ajate             281932.727273     11
Peach Pit         279958.944444     36
Pulp              269204.839080     87
Ludovico Einaudi  266180.250000     28
Chuck Prophet     265579.500000     16
Kasabian          265406.040000     25
Lennie Niehaus    260767.020690    145
Bee Gees          260033.818182     11
El Chicano        257647.882353     17
Rawayana          252338.000000     27
ACHKIRIK          251946.117647     17
Funkadelic        249981.450980     51
Jamiroquai        247289.937500     16
Joaquín Sabina    246563.277638    796
CLUBZ             245186.800000     15
B.B. King         244082.905172    116

In [167]:
# Most Played Tracks
spotify_data['track_name'].value_counts().head(20)

track_name
Ode To The Mets                      207
In the Blood                         181
Dying Breed                          166
Caution                              164
19 Dias y 500 Noches - En Directo    148
For What It's Worth                  146
All These Things That I've Done      142
Concerning Hobbits                   142
Come Together - Remastered 2009      137
The Boxer                            135
Yesterday - Remastered 2009          134
Crucify Your Mind                    131
Mr. Brightside                       128
Reminder                             128
Cavalleria rusticana: Intermezzo     128
Sweet Virginia                       127
I Guess I Just Feel Like             127
Nuovo Cinema Paradiso                127
Imploding The Mirage                 123
Claudia's Theme - Version Eight      123
Name: count, dtype: int64

In [168]:
spotify_data.groupby(['track_name','artist_name'])['ms_played'].sum().sort_values(ascending=False).head(20)

track_name                                                                           artist_name
Ode To The Mets                                                                      The Strokes           67431580
The Return of the King (feat. Sir James Galway, Viggo Mortensen and Renee Fleming)   Howard Shore          64401661
The Fellowship Reunited (feat. Sir James Galway, Viggo Mortensen and Renée Fleming)  Howard Shore          44756730
19 Dias y 500 Noches - En Directo                                                    Joaquín Sabina        42914042
In the Blood                                                                         John Mayer            38427087
Claudia's Theme - Version Eight                                                      Lennie Niehaus        37120900
Dying Breed                                                                          The Killers           36182653
The Breaking of the Fellowship (feat. "In Dreams")                                   Howard Shore          35990898
All These Things That I've Done                                                      The Killers           35754915
Caution                                                                              The Killers           35619945
The Road Goes Ever On..., Pt. 1                                                      Howard Shore          35236377
Epilogue                                                                             Justin Hurwitz        32659024
I Guess I Just Feel Like                                                             John Mayer            29948904
The Journey to the Grey Havens (feat. Sir James Galway)                              Howard Shore          29461194
Visions of Johanna                                                                   Bob Dylan             29152119
100,000 People                                                                       Kings of Leon         28335506
Imploding The Mirage                                                                 The Killers           28034163
Lily, Rosemary and the Jack of Hearts                                                Bob Dylan             27858015
Did My Best                                                                          The Voidz             27814602
Sweet Virginia                                                                       The Rolling Stones    27685640
Name: ms_played, dtype: int64

In [169]:
#top ablums 
#count

spotify_data['album_name'].value_counts().head(20)

album_name
The Beatles                                           2063
Past Masters                                          1672
Abbey Road                                            1429
The Wall                                              1241
Revolver                                              1038
Help!                                                  979
At Folsom Prison                                       918
Sgt. Pepper's Lonely Hearts Club Band                  910
Exile On Main Street                                   892
Hot Fuss                                               878
Where the Light Is: John Mayer Live In Los Angeles     874
Beatles For Sale - Remastered                          833
Rubber Soul                                            827
Sam's Town                                             811
Sawdust                                                778
Chaos And The Calm                                     778
Imploding The Mirage                                   778
Magical Mystery Tour                                   776
Born and Raised                                        765
Blood On The Tracks                                    749
Name: count, dtype: int64

In [170]:
top_album_msplayed = spotify_data.groupby('album_name')['ms_played'].sum()

top_album_msplayed.sort_values(ascending=False).head(20)

album_name
The New Abnormal                                                               186757895
The Beatles                                                                    186649296
Imploding The Mirage                                                           159923361
Abbey Road                                                                     148620310
Blood On The Tracks                                                            147889025
Past Masters                                                                   145024076
Hot Fuss                                                                       144447524
The Wall                                                                       141301809
Where the Light Is: John Mayer Live In Los Angeles                             113814001
Pressure Machine                                                               113324404
Sam's Town                                                                     111994687
Born and Raised                                                                110121624
Exile On Main Street                                                           109051004
Band On The Run                                                                101662064
The Search for Everything                                                      101055737
Magical Mystery Tour                                                           101047280
Continuum                                                                      100640984
The Lord of the Rings: The Fellowship of the Ring - the Complete Recordings     99537879
Sawdust                                                                         96198625
Sgt. Pepper's Lonely Hearts Club Band                                           94931963
Name: ms_played, dtype: int64

In [171]:
#listening over the years

spotify_data['year'].head()

print(spotify_data.groupby('year')['artist_name'].agg(['nunique']))

      nunique
year
2013       63
2014       21
2015      610
2016      458
2017      647
2018      439
2019      493
2020      820
2021     1578
2022     1220
2023     1456
2024     1072

In [172]:
#Favourite artists over the years

favourite_artists = spotify_data.groupby(['year', 'artist_name'])['artist_name'].size().to_frame('artist_count')


top_artists_idx = favourite_artists.groupby(level='year')['artist_count'].idxmax()

top_artists = favourite_artists.loc[top_artists_idx]

print(top_artists)

                  artist_count
year artist_name
2013 John Mayer             34
2014 Blur                    2
2015 The Script            123
2016 The Beatles           715
2017 The Beatles          3244
2018 The Beatles          2006
2019 The Beatles          2015
2020 The Killers          2054
2021 The Beatles          1450
2022 The Beatles           999
2023 The Beatles           730
2024 The Beatles           511

In [173]:
#finding one hit wonders
artist_counts = spotify_data['artist_name'].value_counts()
one_hit_wonders = artist_counts[artist_counts == 1]
one_hit_wonders

artist_name
The Mowgli's             1
Röyksopp                 1
Justice                  1
King Charles             1
Alex Clare               1
                        ..
Doris Day                1
Kyle Mendes Jazz Trio    1
Dinah Washington         1
Smiley Stevens           1
Rudy Snow                1
Name: count, Length: 1850, dtype: int64

In [174]:
# the number of one hit wonders in the dataset
#len(one_hit_wonders) 
one_hit_wonders.shape[0]

1850

In [175]:
# number of unique artists in the dataset
no_of_unique_artists = spotify_data['artist_name'].nunique()
no_of_unique_artists

4113

In [176]:
# percentage of one hit wonders in the dataset
percentage_one_hit_wonders = (one_hit_wonders.shape[0] / no_of_unique_artists) * 100
percentage_one_hit_wonders

44.9793338195964

In [177]:
# one hit wonder tracks
track_counts = spotify_data['track_name'].value_counts()

one_hit_wonder_tracks = track_counts[track_counts == 1]

one_hit_wonder_tracks

track_name
Say It, Just Say It                1
Off To The Races                   1
Half Mast                          1
We Own The Sky                     1
Happy Up Here                      1
                                  ..
Supersonic - Remastered            1
Lola (2020 Stereo Remaster)        1
War Isn't Murder                   1
Oo-De-Lally - From "Robin Hood"    1
King Of The Road                   1
Name: count, Length: 6999, dtype: int64

In [178]:
# number of one  hit wonder tracks in the dataset
one_hit_wonder_tracks.shape[0]

6999

In [179]:
# number of unique tracks in the dataset
total_unique_tracks = spotify_data['track_name'].nunique()
total_unique_tracks

13839

In [180]:
# percentage of one hit wonders in the dataset
percentage_one_hit_wonders = (one_hit_wonder_tracks.shape[0] / total_unique_tracks) * 100
percentage_one_hit_wonders

50.57446347279427